### ISSUE TITLE
Apple watch

### ISSUE THREAD

**Issue by lubieapki** [marcelvoss/PhoneBattery#4]
Something is wrong with the app on the Apple watch
![1](https://cloud.githubusercontent.com/assets/6787484/12425643/1b03acb8-bed6-11e5-8ac8-ce1d4442d942.png)

**Comment by marcelvoss** [comment]
Please use one of the release versions. The in-development has a couple of major bugs at the moment.

**Comment by lubieapki** [comment]
Do you plan updates?

**Comment by marcelvoss** [comment]
I do but I don't have much time to work on it at the moment. You're welcome to contribute though.
